(define (abc086a)
  (let* ((line (read-line (current-input-port)))
         (line (string-split line " "))
         (a (string->number (car line)))
         (b (string->number (car (cdr line)))))
    (if (odd? (* a b))
        (print "Odd")
        (print "Even"))))

(define (abc081a)
  (let* ((line (read-line (current-input-port)))
         (nums (map digit->integer (string->list line))))
    (print (length (filter (lambda (x) (= x 1)) nums)))))

;(abc086a)
(abc081a)